#pragma kernel AppendGrassData

struct GrassData3D 
{
    float3 position;
    float2 uv;
    float displacement;
};
struct CullingData
{
    float3 grassPos;
    float3 camPos;

    float displacement;

    float lodCutoff;
    float cullingBias;
    float cullingBias_Down;
};

RWStructuredBuffer<GrassData3D> grassDataBuffer;
AppendStructuredBuffer<GrassData3D> culledGrassBuffer;

Texture2D<float> _CameraDepthTexture;
SamplerState sampler_CameraDepthTexture;
float4x4 _ViewProjectionMatrix, _CameraProjectionToWorld;

float _TotalInstances;

float3 _CamPos;
float _LODCutoff, _CullingBias, _CullingBias_Down;
float4 _CameraClipPlanes[4];
float _DisplacementStrength;

float3 GetWorldPos(float2 _uv, float _depth)
{
    float4 viewPosH = float4(_uv * 2.0 - 1.0, _depth, 1.0);
    float4 worldPosH = mul(_CameraProjectionToWorld, viewPosH);

    return worldPosH.xyz / worldPosH.w;
}
float2 GetScreenPos(float3 _worldPos)
{
    float4 clipPos  = mul(_ViewProjectionMatrix, float4(_worldPos, 1));
    float3 ndc = clipPos.xyz / clipPos.w;
    return ndc.xy * 0.5 + 0.5;
}
bool IsOccluded(float3 _grassPos, float3 _camPos, float3 _offset)
{
    float2 screenPos = GetScreenPos(_grassPos + _offset);

    float depth = _CameraDepthTexture.SampleLevel(sampler_CameraDepthTexture, screenPos, 0);
    float3 worldPos = GetWorldPos(screenPos, depth);

    float distToGrass = distance(_camPos, _grassPos);
    float distToDepth = distance(_camPos, worldPos);

    return distToDepth < distToGrass;
}
bool IsOcclusionCulled(float3 _grassPos, float3 _camPos, float _displacement)
{
    float boxWidth = 0.75;
    float boxHeight = _displacement;
    float boxDepth = boxWidth;

    const int offsetsCount = 8;
    float3 offsetsArr[offsetsCount] =
    {   
        float3(boxWidth, 0, boxDepth),
        float3(-boxWidth, 0, boxDepth),
        float3(boxWidth, 0, -boxDepth),
        float3(-boxWidth, 0, -boxDepth),
        float3(boxWidth, boxHeight, boxDepth),
        float3(-boxWidth, boxHeight, boxDepth),
        float3(boxWidth, boxHeight, -boxDepth),
        float3(-boxWidth, boxHeight, -boxDepth)
    };
    
    return IsOccluded(_grassPos, _camPos, offsetsArr[0]) &&
           IsOccluded(_grassPos, _camPos, offsetsArr[1]) &&
           IsOccluded(_grassPos, _camPos, offsetsArr[2]) &&
           IsOccluded(_grassPos, _camPos, offsetsArr[3]) &&
           IsOccluded(_grassPos, _camPos, offsetsArr[4]) &&
           IsOccluded(_grassPos, _camPos, offsetsArr[5]) &&
           IsOccluded(_grassPos, _camPos, offsetsArr[6]) &&
           IsOccluded(_grassPos, _camPos, offsetsArr[7]);
}
bool VertexIsBelowClipPlane (float3 _grassPos, int _planeIndex, float _bias) 
{
    float4 plane = _CameraClipPlanes[_planeIndex];
    return dot(float4(_grassPos, 1), plane) < _bias;
}
bool IsFrustumCulled(float3 _grassPos, float _bias, float _bias_down)
{
    return  VertexIsBelowClipPlane(_grassPos, 2, -_bias_down) ||
            VertexIsBelowClipPlane(_grassPos, 0, -_bias) ||
		    VertexIsBelowClipPlane(_grassPos, 1, -_bias) ||
		    VertexIsBelowClipPlane(_grassPos, 3, -_bias);
}
bool IsDistCulled(float3 _grassPos, float3 _camPos, float _lodCutoff)
{
    float dist = distance(_camPos, _grassPos);
    return dist >= _lodCutoff;
}
bool IsCulled(CullingData _data)
{
    return  IsDistCulled(_data.grassPos, _data.camPos, _data.lodCutoff) ||
            IsFrustumCulled(_data.grassPos, _data.cullingBias, _data.cullingBias_Down) ||
            IsOcclusionCulled(_data.grassPos, _data.camPos, _data.displacement);
}

[numthreads(64,1,1)]
void AppendGrassData (uint3 id : SV_DispatchThreadID)
{
    if(id.x >= _TotalInstances) return;

    CullingData data;
    data.grassPos = grassDataBuffer[id.x].position;
    data.camPos = _CamPos;
    data.displacement =  grassDataBuffer[id.x].displacement * _DisplacementStrength;
    data.lodCutoff = _LODCutoff;
    data.cullingBias = _CullingBias;
    data.cullingBias_Down = _CullingBias_Down;

    if(IsCulled(data))
        return;

    culledGrassBuffer.Append(grassDataBuffer[id.x]);
}

